#!/bin/bash

# Copyright 2019 British Broadcasting Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# shellcheck source=get-config.sh
. "$(dirname "${BASH_SOURCE[0]}")/get-config.sh"

set -o errexit

# TODO: Move some of the common/looped code into functions (DRY)

shopt -s nullglob

# Text in this file will appear at the start of the top-level index
INTRO=../intro.md
INTRO_COMMON=.scripts/intro_common.md

# Filename for index in each dir
INDEX=index.md

function add_html_doc {
    doc=$1
    echo "- [${doc%%.html}]($doc)" >> "$INDEX"
};

function do_tree {
    tree=$1
    label=$2 # because of spelling of plurals
    
    echo "Processing $tree $INDEX..."
    (
        cd "$tree" || exit 1
        for dir in */; do
            dirname="${dir%%/}"
            echo "Making $dirname/$INDEX"
            (
                cd "$dir" || exit 1

                    for doc in *.html; do
                        if [[ "$doc" != "index.html" ]]; then
                            add_html_doc "$doc"
                        fi
                    done
            )
        done
    )
}

do_tree branches branch
do_tree releases release

echo "Making top level $INDEX"

# Add lint and render status badges -- with GitHub Actions these default to default branch
default_branch="$(git remote show origin | awk '/HEAD branch/ { print $3 }')"
cat << EOF > "$INDEX"
| Repository | Default Branch | Lint (default) | Render (all) |
| --- | --- | --- | --- |
| [${REPO_ADDRESS##*/}]($REPO_ADDRESS) \
| $default_branch \
| [![Lint Status]($REPO_ADDRESS/workflows/Lint/badge.svg)]($REPO_ADDRESS/actions?query=workflow%3ALint) \
| [![Render Status]($REPO_ADDRESS/workflows/Render/badge.svg)]($REPO_ADDRESS/actions?query=workflow%3ARender) \
|
EOF

# Repo-specific About: section...
{
    echo -e "\n\n---\n\n## About ${AMWA_ID}\n\n"
    cat "$INTRO"
    echo -e "\n\n---\n\n"
} >> "$INDEX"

# Common intro for specs
sed "s~%AMWA_ID%~${AMWA_ID}~g; s~%REPO_ADDRESS%~${REPO_ADDRESS}~g; s~%DEFAULT_TREE%~${DEFAULT_TREE}~g" "$INTRO_COMMON" >> "$INDEX"

# Add the default links at the top - correct the links while copying text
if [ "$DEFAULT_TREE" ]; then
    echo "Adding in contents of $INDEX for default tree $DEFAULT_TREE"
    sed "s:(:($DEFAULT_TREE/:" "$DEFAULT_TREE/$INDEX" >> "$INDEX"
fi

# TODO: DRY on the following...


# These excluded repos don't have branch and releases indexes
    echo Adding branches index...
    INDEX_BRANCHES="branches/index.md"
    echo "## Development Branches" > "$INDEX_BRANCHES"
    echo -e "\n## Development Branches" >> "$INDEX"
    for dir in branches/*; do
        [ ! -d "$dir" ] && continue
        branch="${dir##*/}"
        echo -e "\n[$branch](branches/$branch/)" >>  "$INDEX"
        echo -e "\n[$branch]($branch/)" >>  "$INDEX_BRANCHES"
    done

    echo Adding releases index...
    INDEX_RELEASES="releases/index.md"
    echo "## Published Releases" > "$INDEX_RELEASES"
    echo -e "\n##  Published Releases" >> "$INDEX"
    for dir in releases/*; do
        [ ! -d "$dir" ] && continue
        release="${dir##*/}"
        echo -e "\n[$release](releases/$release/)" >>  "$INDEX"
        echo -e "\n[$release]($release/)" >>  "$INDEX_RELEASES"
    done

echo Adding warnings and project description to each autogenerated file...
find . -name "$INDEX" -exec perl -pi -e 'print "<!-- AUTOGENERATED FILE: DO NOT EDIT -->\n\n# {{ site.github.project_tagline }}\n\n" if $. == 1' {} \;
